apiVersion: v1
kind: Secret
metadata:
  name: alertmanager
  namespace: observability
stringData:
  ALERTMANAGER_PUSHOVER_TOKEN: "a1fmagmv92exoi6khg41n5iiaqkmtc"
  PUSHOVER_USER_KEY: "uh4vxyvayyqsjtudt4xqwzhs6rc3uz"